# Generated by Django 5.2.4 on 2025-07-22 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_save_delete_like"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification", old_name="user", new_name="recipient",
        ),
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.CharField(default="System notification", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("follow", "Follow"), ("save", "Save"), ("post", "New Post")],
                default="post",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.post",
            ),
        ),
    ]
