# Generated by Django 5.2.4 on 2025-07-22 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_user_notification_recipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="favorite_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorited_by",
                to="core.post",
            ),
        ),
    ]
