# Generated by Django 5.2.4 on 2025-07-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_userprofile_favorite_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo_genres",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
