# Generated by Django 5.2.4 on 2025-07-23 07:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
